apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  email-user: {{ .Values.email.user | b64enc | quote }}
  email-password: {{ .Values.email.password | b64enc | quote }}
  admin-user: {{ .Values.admin.user | b64enc | quote }}
  admin-password: {{ .Values.admin.password | b64enc | quote }}
