apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.deployment.replicacount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: POSTGRES_DATABASE
          value: {{ .Values.postgresql.postgresDatabase }}
        - name: POSTGRES_HOST
          {{- if .Values.postgresql.host }}
          value: {{ .Values.postgresql.host }}
          {{- else }}
          value: {{ template "postgresql.fullname" . }}
          {{- end }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresUser }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postgresql.fullname" . }}
              key: postgres-password
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: {{ template "redis.fullname" . }}
        - name: REDIS_PORT
          value: "6379"
        - name: WEBLATE_ADMIN_EMAIL
          value: {{ .Values.admin.email }}
        - name: WEBLATE_ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: admin-password
        - name: WEBLATE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: admin-password
        - name: WEBLATE_EMAIL_HOST
          value: {{ .Values.email.host }}
        - name: WEBLATE_EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: email-user
        - name: WEBLATE_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}
              key: email-password
        {{- range $key, $value := .Values.config }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        volumeMounts:
        - mountPath: {{ .Values.persistence.filestore_dir }}
          name: weblate-data
        # livenessProbe:
        #   failureThreshold: 5
        #   httpGet:
        #     path: /healthz/
        #     port: {{ .Values.service.internalPort }}
        #     scheme: HTTP
        #   initialDelaySeconds: 50
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 2
        # readinessProbe:
        #   failureThreshold: 10
        #   httpGet:
        #     path: /healthz/
        #     port: {{ .Values.service.internalPort }}
        #     scheme: HTTP
        #   initialDelaySeconds: 50
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 2
        resources:
{{ toYaml .Values.deployment.resources | indent 12 }}
      volumes:
      - name: weblate-data
      securityContext:
        fsGroup: 1000
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: weblate-data
    spec:
      accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
      storageClassName: "{{ .Values.persistence.storageClass }}"
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
{{- end }}
